### ISSUE TITLE
k8s service should be generated before deployment

### ISSUE THREAD

**Issue by rwillmer** [vik-y/cookiecutter-django-lite#1]
ref: https://kubernetes.io/docs/concepts/configuration/overview/#services

A very minor nitpick! I'm sending you a PR to make the change.

This is a great idea for a project.

**Comment by vik-y** [comment]
When we are creating the resources manually - we should create `Service` object before `Deployment` but when both the resources are in a single yaml it will still work. 

But thanks for the nitpick and contribution. I'll pass it through :)
